@startuml SpaceRace

class Cohete 
class Asteroide
class Borde
class Controlador
class Pantalla
class Puntaje
class CoheteEnemigo
class Fin
class Animacion
class Muerte
class Patron
class Tiempo
class Posicion
class Cordenada
class Imagen

Pantalla *-- Puntaje
Pantalla *-- Cohete
Pantalla *-- Borde
Pantalla --o Controlador
Pantalla *-- Asteroide
Pantalla *-- CoheteEnemigo
Pantalla *-- Fin
Pantalla --o Animacion 

Cohete o-- Controlador
Cohete --* Puntaje
Cohete o--Asteroide
Cohete --* Posicion
Cohete --|> Imagen

CoheteEnemigo --* Puntaje
CoheteEnemigo o--Asteroide
CoheteEnemigo --* Patron
CoheteEnemigo --* Puntaje
CoheteEnemigo --* Posicion
CoheteEnemigo --|> Imagen

Asteroide o-- Animacion
Asteroide --|> Muerte
Asteroide --* Patron
Asteroide o--Borde
Asteroide --*Posicion
Asteroide --|> Imagen

Imagen --o Animacion
Controlador o-- Posicion
Posicion --* Cordenada
Patron --* Tiempo
Fin --o Puntaje

@enduml